# Generated by Django 3.0.8 on 2020-08-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='serial_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
